/*
 * Copyright 2022-2024 BG Information Systems Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 */
   
package com.bginfosys.dinghyracing.persistence;

import java.time.LocalDateTime;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.format.annotation.DateTimeFormat;

import com.bginfosys.dinghyracing.model.Race;

public interface RaceRepository extends JpaRepository<Race, Long> {

//	@Override
//	void deleteById(@Param("id") Long id);

//	@Override
//	void delete(@Param("race") Race race);
	
//	Page<Race> findByPlannedStartTimeGreaterThanEqual(@Param("time") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime time, Pageable pageable);
	
	// May be an issue with this query and the way Hibernate identifies the class to be instantiated.
	// _clazz field is normally generated by Hibernate to track the class to be created. 0 indicates parent class and 1 a subclass.
	// Hibernate(?) appears to be identifying 0 as DirectRace. and so additional fields required to instantiate a DirectRace have had to be included.
	// Is a better (tidier/ less fudged) solution via Hibernate configuration?
	@Query(value = "SELECT id, fleet_id, name, last_lead_entry_id, last_lead_entry_laps_completed, 0 as duration, 0 as planned_laps, planned_start_time, start_time_offset, version, null as start_type, null as type, 0 as clazz_"
			+ " FROM (SELECT race.id, race.fleet_id, race.name, race.last_lead_entry_id, race.last_lead_entry_laps_completed, race.version, MIN(planned_start_time.planned_start_time) AS planned_start_time"
			+ ", MIN(planned_start_time.start_time_offset) AS start_time_offset"
			+ " FROM dinghy_racing.race"
			+ "	LEFT JOIN (SELECT embedded_race_hosts.embedded_race_id AS id, planned_start_time AS planned_start_time, start_time_offset AS start_time_offset"
			+ "				FROM direct_race"
			+ "					LEFT JOIN embedded_race_hosts ON direct_race.id = embedded_race_hosts.hosts_id"
			+ "			) AS planned_start_time ON race.id = planned_start_time.id"
			+ "    LEFT JOIN embedded_race_hosts ON planned_start_time.id = embedded_race_hosts.hosts_id"
			+ " WHERE planned_start_time IS NOT NULL"
			+ " GROUP BY race.id, race.fleet_id, race.name, race.last_lead_entry_id, race.last_lead_entry_laps_completed, race.version"
			+ " UNION"
			+ " SELECT race.id, race.fleet_id, race.name, race.last_lead_entry_id, race.last_lead_entry_laps_completed, race.version, direct_race.planned_start_time, direct_race.start_time_offset"
			+ " FROM race"
			+ "	LEFT JOIN direct_race ON race.id = direct_race.id"
			+ " WHERE planned_start_time IS NOT NULL) AS all_races"
			+ " WHERE planned_start_time >= :startTime AND planned_start_time <= :endTime;", nativeQuery = true)
	Page<Race> findByPlannedStartTimeBetween(@Param("startTime") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime startTime, 
			@Param("endTime") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime endTime, Pageable pageable);

//	Page<Race> findByPlannedStartTimeBetweenAndTypeEquals(@Param("startTime") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime startTime, 
//			@Param("endTime") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime endTime, @Param("type") RaceType type, Pageable pageable);
}
